name: Generate 3D Profile Contributions

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight

jobs:
  generate-3d-contrib:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate 3D Contribution Graph
        run: |
          git clone https://github.com/yoshi389111/github-profile-3d-contrib.git
          cd github-profile-3d-contrib
          npm install
          USERNAME=ComradeMohan node index.js --output ../profile-3d-contrib --theme "night-rainbow"

      - name: Push to GitHub
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add -A
          git commit -m "Update 3D contribution graph" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
