name: Update LeetCode Cards

on:
  schedule:
    - cron: "30 7 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create folder
        run: mkdir -p assets/leetcode

      - name: Download Dark Card
        run: |
          curl -L \
          "https://leetcard.jacoblin.cool/comrademohan?theme=dark&ext=heatmap" \
          -o assets/leetcode/leetcode-dark.svg

      - name: Download Light Card
        run: |
          curl -L \
          "https://leetcard.jacoblin.cool/comrademohan?theme=default&ext=heatmap" \
          -o assets/leetcode/leetcode-light.svg

      - name: Patch SVGs
        run: |
          sed -i 's/svg{opacity:0}/svg{opacity:1}/' assets/leetcode/leetcode-dark.svg
          sed -i 's/svg{opacity:0}/svg{opacity:1}/' assets/leetcode/leetcode-light.svg

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add assets/leetcode/*.svg

          git diff --cached --quiet && exit 0

          git commit -m "chore: update LeetCode cards"

          git push
